/*-------------------------------------------------------------------------
 *
 * outfast.switch.c
 *    Generated node infrastructure code
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/nodes/gen_node_support.pl
 *
 *-------------------------------------------------------------------------
 */
		case T_GpPolicy:
			_outGpPolicy(str, obj);
			break;
		case T_Alias:
			_outAlias(str, obj);
			break;
		case T_RangeVar:
			_outRangeVar(str, obj);
			break;
		case T_TableFunc:
			_outTableFunc(str, obj);
			break;
		case T_IntoClause:
			_outIntoClause(str, obj);
			break;
		case T_CopyIntoClause:
			_outCopyIntoClause(str, obj);
			break;
		case T_RefreshClause:
			_outRefreshClause(str, obj);
			break;
		case T_Var:
			_outVar(str, obj);
			break;
		case T_Param:
			_outParam(str, obj);
			break;
		case T_Aggref:
			_outAggref(str, obj);
			break;
		case T_GroupId:
			_outGroupId(str, obj);
			break;
		case T_GroupingSetId:
			_outGroupingSetId(str, obj);
			break;
		case T_AggExprId:
			_outAggExprId(str, obj);
			break;
		case T_RowIdExpr:
			_outRowIdExpr(str, obj);
			break;
		case T_GroupingFunc:
			_outGroupingFunc(str, obj);
			break;
		case T_WindowFunc:
			_outWindowFunc(str, obj);
			break;
		case T_SubscriptingRef:
			_outSubscriptingRef(str, obj);
			break;
		case T_FuncExpr:
			_outFuncExpr(str, obj);
			break;
		case T_NamedArgExpr:
			_outNamedArgExpr(str, obj);
			break;
		case T_OpExpr:
			_outOpExpr(str, obj);
			break;
		case T_DistinctExpr:
			_outDistinctExpr(str, obj);
			break;
		case T_NullIfExpr:
			_outNullIfExpr(str, obj);
			break;
		case T_ScalarArrayOpExpr:
			_outScalarArrayOpExpr(str, obj);
			break;
		case T_TableValueExpr:
			_outTableValueExpr(str, obj);
			break;
		case T_SubLink:
			_outSubLink(str, obj);
			break;
		case T_SubPlan:
			_outSubPlan(str, obj);
			break;
		case T_AlternativeSubPlan:
			_outAlternativeSubPlan(str, obj);
			break;
		case T_FieldSelect:
			_outFieldSelect(str, obj);
			break;
		case T_FieldStore:
			_outFieldStore(str, obj);
			break;
		case T_RelabelType:
			_outRelabelType(str, obj);
			break;
		case T_CoerceViaIO:
			_outCoerceViaIO(str, obj);
			break;
		case T_ArrayCoerceExpr:
			_outArrayCoerceExpr(str, obj);
			break;
		case T_ConvertRowtypeExpr:
			_outConvertRowtypeExpr(str, obj);
			break;
		case T_CollateExpr:
			_outCollateExpr(str, obj);
			break;
		case T_CaseExpr:
			_outCaseExpr(str, obj);
			break;
		case T_CaseWhen:
			_outCaseWhen(str, obj);
			break;
		case T_CaseTestExpr:
			_outCaseTestExpr(str, obj);
			break;
		case T_ArrayExpr:
			_outArrayExpr(str, obj);
			break;
		case T_RowExpr:
			_outRowExpr(str, obj);
			break;
		case T_RowCompareExpr:
			_outRowCompareExpr(str, obj);
			break;
		case T_CoalesceExpr:
			_outCoalesceExpr(str, obj);
			break;
		case T_MinMaxExpr:
			_outMinMaxExpr(str, obj);
			break;
		case T_SQLValueFunction:
			_outSQLValueFunction(str, obj);
			break;
		case T_XmlExpr:
			_outXmlExpr(str, obj);
			break;
		case T_JsonFormat:
			_outJsonFormat(str, obj);
			break;
		case T_JsonReturning:
			_outJsonReturning(str, obj);
			break;
		case T_JsonValueExpr:
			_outJsonValueExpr(str, obj);
			break;
		case T_JsonConstructorExpr:
			_outJsonConstructorExpr(str, obj);
			break;
		case T_JsonIsPredicate:
			_outJsonIsPredicate(str, obj);
			break;
		case T_NullTest:
			_outNullTest(str, obj);
			break;
		case T_BooleanTest:
			_outBooleanTest(str, obj);
			break;
		case T_CoerceToDomain:
			_outCoerceToDomain(str, obj);
			break;
		case T_CoerceToDomainValue:
			_outCoerceToDomainValue(str, obj);
			break;
		case T_SetToDefault:
			_outSetToDefault(str, obj);
			break;
		case T_CurrentOfExpr:
			_outCurrentOfExpr(str, obj);
			break;
		case T_NextValueExpr:
			_outNextValueExpr(str, obj);
			break;
		case T_InferenceElem:
			_outInferenceElem(str, obj);
			break;
		case T_TargetEntry:
			_outTargetEntry(str, obj);
			break;
		case T_RangeTblRef:
			_outRangeTblRef(str, obj);
			break;
		case T_JoinExpr:
			_outJoinExpr(str, obj);
			break;
		case T_FromExpr:
			_outFromExpr(str, obj);
			break;
		case T_OnConflictExpr:
			_outOnConflictExpr(str, obj);
			break;
		case T_DMLActionExpr:
			_outDMLActionExpr(str, obj);
			break;
		case T_ColumnRef:
			_outColumnRef(str, obj);
			break;
		case T_ParamRef:
			_outParamRef(str, obj);
			break;
		case T_RoleSpec:
			_outRoleSpec(str, obj);
			break;
		case T_A_Star:
			_outA_Star(str, obj);
			break;
		case T_A_Indices:
			_outA_Indices(str, obj);
			break;
		case T_A_Indirection:
			_outA_Indirection(str, obj);
			break;
		case T_A_ArrayExpr:
			_outA_ArrayExpr(str, obj);
			break;
		case T_ResTarget:
			_outResTarget(str, obj);
			break;
		case T_MultiAssignRef:
			_outMultiAssignRef(str, obj);
			break;
		case T_SortBy:
			_outSortBy(str, obj);
			break;
		case T_WindowDef:
			_outWindowDef(str, obj);
			break;
		case T_RangeTableSample:
			_outRangeTableSample(str, obj);
			break;
		case T_ColumnReferenceStorageDirective:
			_outColumnReferenceStorageDirective(str, obj);
			break;
		case T_DistributionKeyElem:
			_outDistributionKeyElem(str, obj);
			break;
		case T_PartitionElem:
			_outPartitionElem(str, obj);
			break;
		case T_PartitionSpec:
			_outPartitionSpec(str, obj);
			break;
		case T_PartitionBoundSpec:
			_outPartitionBoundSpec(str, obj);
			break;
		case T_PartitionRangeDatum:
			_outPartitionRangeDatum(str, obj);
			break;
		case T_PartitionCmd:
			_outPartitionCmd(str, obj);
			break;
		case T_RTEPermissionInfo:
			_outRTEPermissionInfo(str, obj);
			break;
		case T_TableSampleClause:
			_outTableSampleClause(str, obj);
			break;
		case T_WithCheckOption:
			_outWithCheckOption(str, obj);
			break;
		case T_SortGroupClause:
			_outSortGroupClause(str, obj);
			break;
		case T_GroupingSet:
			_outGroupingSet(str, obj);
			break;
		case T_WindowClause:
			_outWindowClause(str, obj);
			break;
		case T_RowMarkClause:
			_outRowMarkClause(str, obj);
			break;
		case T_WithClause:
			_outWithClause(str, obj);
			break;
		case T_InferClause:
			_outInferClause(str, obj);
			break;
		case T_OnConflictClause:
			_outOnConflictClause(str, obj);
			break;
		case T_CTESearchClause:
			_outCTESearchClause(str, obj);
			break;
		case T_CTECycleClause:
			_outCTECycleClause(str, obj);
			break;
		case T_CommonTableExpr:
			_outCommonTableExpr(str, obj);
			break;
		case T_MergeWhenClause:
			_outMergeWhenClause(str, obj);
			break;
		case T_MergeAction:
			_outMergeAction(str, obj);
			break;
		case T_JsonOutput:
			_outJsonOutput(str, obj);
			break;
		case T_JsonKeyValue:
			_outJsonKeyValue(str, obj);
			break;
		case T_JsonObjectConstructor:
			_outJsonObjectConstructor(str, obj);
			break;
		case T_JsonArrayConstructor:
			_outJsonArrayConstructor(str, obj);
			break;
		case T_JsonArrayQueryConstructor:
			_outJsonArrayQueryConstructor(str, obj);
			break;
		case T_JsonAggConstructor:
			_outJsonAggConstructor(str, obj);
			break;
		case T_JsonObjectAgg:
			_outJsonObjectAgg(str, obj);
			break;
		case T_JsonArrayAgg:
			_outJsonArrayAgg(str, obj);
			break;
		case T_RawStmt:
			_outRawStmt(str, obj);
			break;
		case T_DeleteStmt:
			_outDeleteStmt(str, obj);
			break;
		case T_UpdateStmt:
			_outUpdateStmt(str, obj);
			break;
		case T_MergeStmt:
			_outMergeStmt(str, obj);
			break;
		case T_DistributedBy:
			_outDistributedBy(str, obj);
			break;
		case T_SetOperationStmt:
			_outSetOperationStmt(str, obj);
			break;
		case T_ReturnStmt:
			_outReturnStmt(str, obj);
			break;
		case T_CreateSchemaStmt:
			_outCreateSchemaStmt(str, obj);
			break;
		case T_AlterSchemaStmt:
			_outAlterSchemaStmt(str, obj);
			break;
		case T_CreateTagStmt:
			_outCreateTagStmt(str, obj);
			break;
		case T_CompoundUtilityStmt:
			_outCompoundUtilityStmt(str, obj);
			break;
		case T_AlterTableStmt:
			_outAlterTableStmt(str, obj);
			break;
		case T_AlterTagStmt:
			_outAlterTagStmt(str, obj);
			break;
		case T_ReplicaIdentityStmt:
			_outReplicaIdentityStmt(str, obj);
			break;
		case T_AlterTableCmd:
			_outAlterTableCmd(str, obj);
			break;
		case T_GpAlterPartitionId:
			_outGpAlterPartitionId(str, obj);
			break;
		case T_GpDropPartitionCmd:
			_outGpDropPartitionCmd(str, obj);
			break;
		case T_GpAlterPartitionCmd:
			_outGpAlterPartitionCmd(str, obj);
			break;
		case T_GpPartitionRangeItem:
			_outGpPartitionRangeItem(str, obj);
			break;
		case T_GpSplitPartitionCmd:
			_outGpSplitPartitionCmd(str, obj);
			break;
		case T_AlterCollationStmt:
			_outAlterCollationStmt(str, obj);
			break;
		case T_AlterDomainStmt:
			_outAlterDomainStmt(str, obj);
			break;
		case T_GrantStmt:
			_outGrantStmt(str, obj);
			break;
		case T_ObjectWithArgs:
			_outObjectWithArgs(str, obj);
			break;
		case T_AccessPriv:
			_outAccessPriv(str, obj);
			break;
		case T_GrantRoleStmt:
			_outGrantRoleStmt(str, obj);
			break;
		case T_SingleRowErrorDesc:
			_outSingleRowErrorDesc(str, obj);
			break;
		case T_AlterDefaultPrivilegesStmt:
			_outAlterDefaultPrivilegesStmt(str, obj);
			break;
		case T_VariableSetStmt:
			_outVariableSetStmt(str, obj);
			break;
		case T_VariableShowStmt:
			_outVariableShowStmt(str, obj);
			break;
		case T_ExtTableTypeDesc:
			_outExtTableTypeDesc(str, obj);
			break;
		case T_CreateExternalStmt:
			_outCreateExternalStmt(str, obj);
			break;
		case T_CreateForeignStmt:
			_outCreateForeignStmt(str, obj);
			break;
		case T_GpPartDefElem:
			_outGpPartDefElem(str, obj);
			break;
		case T_GpPartitionRangeSpec:
			_outGpPartitionRangeSpec(str, obj);
			break;
		case T_GpPartitionListSpec:
			_outGpPartitionListSpec(str, obj);
			break;
		case T_GpPartitionDefinition:
			_outGpPartitionDefinition(str, obj);
			break;
		case T_CreateTableSpaceStmt:
			_outCreateTableSpaceStmt(str, obj);
			break;
		case T_DropTableSpaceStmt:
			_outDropTableSpaceStmt(str, obj);
			break;
		case T_AlterTableSpaceOptionsStmt:
			_outAlterTableSpaceOptionsStmt(str, obj);
			break;
		case T_AlterTableMoveAllStmt:
			_outAlterTableMoveAllStmt(str, obj);
			break;
		case T_DropTagStmt:
			_outDropTagStmt(str, obj);
			break;
		case T_CreateTaskStmt:
			_outCreateTaskStmt(str, obj);
			break;
		case T_AlterTaskStmt:
			_outAlterTaskStmt(str, obj);
			break;
		case T_DropTaskStmt:
			_outDropTaskStmt(str, obj);
			break;
		case T_CreateExtensionStmt:
			_outCreateExtensionStmt(str, obj);
			break;
		case T_AlterExtensionStmt:
			_outAlterExtensionStmt(str, obj);
			break;
		case T_AlterExtensionContentsStmt:
			_outAlterExtensionContentsStmt(str, obj);
			break;
		case T_CreateFdwStmt:
			_outCreateFdwStmt(str, obj);
			break;
		case T_AlterFdwStmt:
			_outAlterFdwStmt(str, obj);
			break;
		case T_CreateForeignServerStmt:
			_outCreateForeignServerStmt(str, obj);
			break;
		case T_AlterForeignServerStmt:
			_outAlterForeignServerStmt(str, obj);
			break;
		case T_CreateStorageServerStmt:
			_outCreateStorageServerStmt(str, obj);
			break;
		case T_AlterStorageServerStmt:
			_outAlterStorageServerStmt(str, obj);
			break;
		case T_DropStorageServerStmt:
			_outDropStorageServerStmt(str, obj);
			break;
		case T_CreateUserMappingStmt:
			_outCreateUserMappingStmt(str, obj);
			break;
		case T_AlterUserMappingStmt:
			_outAlterUserMappingStmt(str, obj);
			break;
		case T_DropUserMappingStmt:
			_outDropUserMappingStmt(str, obj);
			break;
		case T_CreateStorageUserMappingStmt:
			_outCreateStorageUserMappingStmt(str, obj);
			break;
		case T_AlterStorageUserMappingStmt:
			_outAlterStorageUserMappingStmt(str, obj);
			break;
		case T_DropStorageUserMappingStmt:
			_outDropStorageUserMappingStmt(str, obj);
			break;
		case T_ImportForeignSchemaStmt:
			_outImportForeignSchemaStmt(str, obj);
			break;
		case T_AddForeignSegStmt:
			_outAddForeignSegStmt(str, obj);
			break;
		case T_CreatePolicyStmt:
			_outCreatePolicyStmt(str, obj);
			break;
		case T_AlterPolicyStmt:
			_outAlterPolicyStmt(str, obj);
			break;
		case T_CreateAmStmt:
			_outCreateAmStmt(str, obj);
			break;
		case T_CreateEventTrigStmt:
			_outCreateEventTrigStmt(str, obj);
			break;
		case T_AlterEventTrigStmt:
			_outAlterEventTrigStmt(str, obj);
			break;
		case T_CreatePLangStmt:
			_outCreatePLangStmt(str, obj);
			break;
		case T_CreateQueueStmt:
			_outCreateQueueStmt(str, obj);
			break;
		case T_AlterQueueStmt:
			_outAlterQueueStmt(str, obj);
			break;
		case T_DropQueueStmt:
			_outDropQueueStmt(str, obj);
			break;
		case T_CreateResourceGroupStmt:
			_outCreateResourceGroupStmt(str, obj);
			break;
		case T_DropResourceGroupStmt:
			_outDropResourceGroupStmt(str, obj);
			break;
		case T_AlterResourceGroupStmt:
			_outAlterResourceGroupStmt(str, obj);
			break;
		case T_CreateRoleStmt:
			_outCreateRoleStmt(str, obj);
			break;
		case T_AlterRoleStmt:
			_outAlterRoleStmt(str, obj);
			break;
		case T_AlterRoleSetStmt:
			_outAlterRoleSetStmt(str, obj);
			break;
		case T_DropRoleStmt:
			_outDropRoleStmt(str, obj);
			break;
		case T_CreateProfileStmt:
			_outCreateProfileStmt(str, obj);
			break;
		case T_AlterProfileStmt:
			_outAlterProfileStmt(str, obj);
			break;
		case T_DropProfileStmt:
			_outDropProfileStmt(str, obj);
			break;
		case T_DenyLoginPoint:
			_outDenyLoginPoint(str, obj);
			break;
		case T_DenyLoginInterval:
			_outDenyLoginInterval(str, obj);
			break;
		case T_CreateSeqStmt:
			_outCreateSeqStmt(str, obj);
			break;
		case T_AlterSeqStmt:
			_outAlterSeqStmt(str, obj);
			break;
		case T_DefineStmt:
			_outDefineStmt(str, obj);
			break;
		case T_CreateDomainStmt:
			_outCreateDomainStmt(str, obj);
			break;
		case T_CreateOpClassStmt:
			_outCreateOpClassStmt(str, obj);
			break;
		case T_CreateOpClassItem:
			_outCreateOpClassItem(str, obj);
			break;
		case T_CreateOpFamilyStmt:
			_outCreateOpFamilyStmt(str, obj);
			break;
		case T_AlterOpFamilyStmt:
			_outAlterOpFamilyStmt(str, obj);
			break;
		case T_AlterDirectoryTableStmt:
			_outAlterDirectoryTableStmt(str, obj);
			break;
		case T_DropStmt:
			_outDropStmt(str, obj);
			break;
		case T_DropDirectoryTableStmt:
			_outDropDirectoryTableStmt(str, obj);
			break;
		case T_TruncateStmt:
			_outTruncateStmt(str, obj);
			break;
		case T_CommentStmt:
			_outCommentStmt(str, obj);
			break;
		case T_SecLabelStmt:
			_outSecLabelStmt(str, obj);
			break;
		case T_DeclareCursorStmt:
			_outDeclareCursorStmt(str, obj);
			break;
		case T_ClosePortalStmt:
			_outClosePortalStmt(str, obj);
			break;
		case T_FetchStmt:
			_outFetchStmt(str, obj);
			break;
		case T_IndexStmt:
			_outIndexStmt(str, obj);
			break;
		case T_CreateStatsStmt:
			_outCreateStatsStmt(str, obj);
			break;
		case T_AlterStatsStmt:
			_outAlterStatsStmt(str, obj);
			break;
		case T_CreateFunctionStmt:
			_outCreateFunctionStmt(str, obj);
			break;
		case T_FunctionParameter:
			_outFunctionParameter(str, obj);
			break;
		case T_AlterFunctionStmt:
			_outAlterFunctionStmt(str, obj);
			break;
		case T_DoStmt:
			_outDoStmt(str, obj);
			break;
		case T_CallStmt:
			_outCallStmt(str, obj);
			break;
		case T_RenameStmt:
			_outRenameStmt(str, obj);
			break;
		case T_AlterObjectDependsStmt:
			_outAlterObjectDependsStmt(str, obj);
			break;
		case T_AlterObjectSchemaStmt:
			_outAlterObjectSchemaStmt(str, obj);
			break;
		case T_AlterOwnerStmt:
			_outAlterOwnerStmt(str, obj);
			break;
		case T_AlterOperatorStmt:
			_outAlterOperatorStmt(str, obj);
			break;
		case T_AlterTypeStmt:
			_outAlterTypeStmt(str, obj);
			break;
		case T_RuleStmt:
			_outRuleStmt(str, obj);
			break;
		case T_NotifyStmt:
			_outNotifyStmt(str, obj);
			break;
		case T_ListenStmt:
			_outListenStmt(str, obj);
			break;
		case T_UnlistenStmt:
			_outUnlistenStmt(str, obj);
			break;
		case T_TransactionStmt:
			_outTransactionStmt(str, obj);
			break;
		case T_CompositeTypeStmt:
			_outCompositeTypeStmt(str, obj);
			break;
		case T_CreateEnumStmt:
			_outCreateEnumStmt(str, obj);
			break;
		case T_CreateRangeStmt:
			_outCreateRangeStmt(str, obj);
			break;
		case T_AlterEnumStmt:
			_outAlterEnumStmt(str, obj);
			break;
		case T_ViewStmt:
			_outViewStmt(str, obj);
			break;
		case T_LoadStmt:
			_outLoadStmt(str, obj);
			break;
		case T_CreatedbStmt:
			_outCreatedbStmt(str, obj);
			break;
		case T_AlterDatabaseStmt:
			_outAlterDatabaseStmt(str, obj);
			break;
		case T_AlterDatabaseRefreshCollStmt:
			_outAlterDatabaseRefreshCollStmt(str, obj);
			break;
		case T_AlterDatabaseSetStmt:
			_outAlterDatabaseSetStmt(str, obj);
			break;
		case T_DropdbStmt:
			_outDropdbStmt(str, obj);
			break;
		case T_AlterSystemStmt:
			_outAlterSystemStmt(str, obj);
			break;
		case T_ClusterStmt:
			_outClusterStmt(str, obj);
			break;
		case T_VacuumStmt:
			_outVacuumStmt(str, obj);
			break;
		case T_VacuumRelation:
			_outVacuumRelation(str, obj);
			break;
		case T_ExplainStmt:
			_outExplainStmt(str, obj);
			break;
		case T_CreateTableAsStmt:
			_outCreateTableAsStmt(str, obj);
			break;
		case T_RefreshMatViewStmt:
			_outRefreshMatViewStmt(str, obj);
			break;
		case T_CheckPointStmt:
			_outCheckPointStmt(str, obj);
			break;
		case T_DiscardStmt:
			_outDiscardStmt(str, obj);
			break;
		case T_LockStmt:
			_outLockStmt(str, obj);
			break;
		case T_ConstraintsSetStmt:
			_outConstraintsSetStmt(str, obj);
			break;
		case T_ReindexIndexInfo:
			_outReindexIndexInfo(str, obj);
			break;
		case T_ReindexStmt:
			_outReindexStmt(str, obj);
			break;
		case T_CreateConversionStmt:
			_outCreateConversionStmt(str, obj);
			break;
		case T_CreateCastStmt:
			_outCreateCastStmt(str, obj);
			break;
		case T_CreateTransformStmt:
			_outCreateTransformStmt(str, obj);
			break;
		case T_PrepareStmt:
			_outPrepareStmt(str, obj);
			break;
		case T_ExecuteStmt:
			_outExecuteStmt(str, obj);
			break;
		case T_DeallocateStmt:
			_outDeallocateStmt(str, obj);
			break;
		case T_DropOwnedStmt:
			_outDropOwnedStmt(str, obj);
			break;
		case T_ReassignOwnedStmt:
			_outReassignOwnedStmt(str, obj);
			break;
		case T_AlterTSDictionaryStmt:
			_outAlterTSDictionaryStmt(str, obj);
			break;
		case T_PublicationTable:
			_outPublicationTable(str, obj);
			break;
		case T_PublicationObjSpec:
			_outPublicationObjSpec(str, obj);
			break;
		case T_CreatePublicationStmt:
			_outCreatePublicationStmt(str, obj);
			break;
		case T_AlterPublicationStmt:
			_outAlterPublicationStmt(str, obj);
			break;
		case T_CreateSubscriptionStmt:
			_outCreateSubscriptionStmt(str, obj);
			break;
		case T_AlterSubscriptionStmt:
			_outAlterSubscriptionStmt(str, obj);
			break;
		case T_DropSubscriptionStmt:
			_outDropSubscriptionStmt(str, obj);
			break;
		case T_RetrieveStmt:
			_outRetrieveStmt(str, obj);
			break;
		case T_CreateWarehouseStmt:
			_outCreateWarehouseStmt(str, obj);
			break;
		case T_DropWarehouseStmt:
			_outDropWarehouseStmt(str, obj);
			break;
		case T_RelAggInfo:
			_outRelAggInfo(str, obj);
			break;
		case T_PlaceHolderVar:
			_outPlaceHolderVar(str, obj);
			break;
		case T_AppendRelInfo:
			_outAppendRelInfo(str, obj);
			break;
		case T_GroupedVarInfo:
			_outGroupedVarInfo(str, obj);
			break;
		case T_SegfileMapNode:
			_outSegfileMapNode(str, obj);
			break;
		case T_ExternalScanInfo:
			_outExternalScanInfo(str, obj);
			break;
		case T_NestLoopParam:
			_outNestLoopParam(str, obj);
			break;
		case T_PlanRowMark:
			_outPlanRowMark(str, obj);
			break;
		case T_PartitionPruneInfo:
			_outPartitionPruneInfo(str, obj);
			break;
		case T_PartitionedRelPruneInfo:
			_outPartitionedRelPruneInfo(str, obj);
			break;
		case T_PartitionPruneStepOp:
			_outPartitionPruneStepOp(str, obj);
			break;
		case T_PartitionPruneStepCombine:
			_outPartitionPruneStepCombine(str, obj);
			break;
